package com.wyl.tms.model;

public class ChildGoodsOrder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column child_goods_order.childGoodsOrderId
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    private Integer childGoodsOrderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column child_goods_order.goodsId
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    private Integer goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column child_goods_order.quantity
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    private Integer quantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column child_goods_order.priceSum
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    private Double priceSum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column child_goods_order.childGoodsOrderId
     *
     * @return the value of child_goods_order.childGoodsOrderId
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public Integer getChildGoodsOrderId() {
        return childGoodsOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column child_goods_order.childGoodsOrderId
     *
     * @param childGoodsOrderId the value for child_goods_order.childGoodsOrderId
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public void setChildGoodsOrderId(Integer childGoodsOrderId) {
        this.childGoodsOrderId = childGoodsOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column child_goods_order.goodsId
     *
     * @return the value of child_goods_order.goodsId
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column child_goods_order.goodsId
     *
     * @param goodsId the value for child_goods_order.goodsId
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column child_goods_order.quantity
     *
     * @return the value of child_goods_order.quantity
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column child_goods_order.quantity
     *
     * @param quantity the value for child_goods_order.quantity
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column child_goods_order.priceSum
     *
     * @return the value of child_goods_order.priceSum
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public Double getPriceSum() {
        return priceSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column child_goods_order.priceSum
     *
     * @param priceSum the value for child_goods_order.priceSum
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public void setPriceSum(Double priceSum) {
        this.priceSum = priceSum;
    }
}