package com.wyl.tms.model;

public class CouponType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon_type.couponTypeId
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    private Integer couponTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon_type.commodityType
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    private Boolean commodityType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon_type.couponDescription
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    private String couponDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon_type.validityPeriod
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    private Integer validityPeriod;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon_type.couponTypeId
     *
     * @return the value of coupon_type.couponTypeId
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public Integer getCouponTypeId() {
        return couponTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon_type.couponTypeId
     *
     * @param couponTypeId the value for coupon_type.couponTypeId
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public void setCouponTypeId(Integer couponTypeId) {
        this.couponTypeId = couponTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon_type.commodityType
     *
     * @return the value of coupon_type.commodityType
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public Boolean getCommodityType() {
        return commodityType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon_type.commodityType
     *
     * @param commodityType the value for coupon_type.commodityType
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public void setCommodityType(Boolean commodityType) {
        this.commodityType = commodityType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon_type.couponDescription
     *
     * @return the value of coupon_type.couponDescription
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public String getCouponDescription() {
        return couponDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon_type.couponDescription
     *
     * @param couponDescription the value for coupon_type.couponDescription
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public void setCouponDescription(String couponDescription) {
        this.couponDescription = couponDescription == null ? null : couponDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon_type.validityPeriod
     *
     * @return the value of coupon_type.validityPeriod
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public Integer getValidityPeriod() {
        return validityPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon_type.validityPeriod
     *
     * @param validityPeriod the value for coupon_type.validityPeriod
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public void setValidityPeriod(Integer validityPeriod) {
        this.validityPeriod = validityPeriod;
    }
}