package com.wyl.tms.model;

import java.util.Date;

public class FilmArrangement {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column film_arrangement.arrangementId
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    private Integer arrangementId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column film_arrangement.filmId
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    private Integer filmId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column film_arrangement.filmHallNumber
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    private Integer filmHallNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column film_arrangement.date
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column film_arrangement.time
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column film_arrangement.arrangementId
     *
     * @return the value of film_arrangement.arrangementId
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public Integer getArrangementId() {
        return arrangementId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column film_arrangement.arrangementId
     *
     * @param arrangementId the value for film_arrangement.arrangementId
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public void setArrangementId(Integer arrangementId) {
        this.arrangementId = arrangementId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column film_arrangement.filmId
     *
     * @return the value of film_arrangement.filmId
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public Integer getFilmId() {
        return filmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column film_arrangement.filmId
     *
     * @param filmId the value for film_arrangement.filmId
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public void setFilmId(Integer filmId) {
        this.filmId = filmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column film_arrangement.filmHallNumber
     *
     * @return the value of film_arrangement.filmHallNumber
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public Integer getFilmHallNumber() {
        return filmHallNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column film_arrangement.filmHallNumber
     *
     * @param filmHallNumber the value for film_arrangement.filmHallNumber
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public void setFilmHallNumber(Integer filmHallNumber) {
        this.filmHallNumber = filmHallNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column film_arrangement.date
     *
     * @return the value of film_arrangement.date
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column film_arrangement.date
     *
     * @param date the value for film_arrangement.date
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column film_arrangement.time
     *
     * @return the value of film_arrangement.time
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column film_arrangement.time
     *
     * @param time the value for film_arrangement.time
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public void setTime(Date time) {
        this.time = time;
    }
}