package com.wyl.tms.model;

import com.baomidou.mybatisplus.annotations.TableId;
import com.baomidou.mybatisplus.enums.IdType;
import com.fasterxml.jackson.annotation.JsonFormat;
import lombok.Data;

import java.util.Date;

@Data
public class FilmArrangement {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column film_arrangement.arrangementId
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    @TableId(value = "arrangement_id", type = IdType.AUTO)
    private Integer arrangementId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column film_arrangement.filmId
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    private Integer filmId;

    private Double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column film_arrangement.filmHallNumber
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    private Integer filmHallNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column film_arrangement.date
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    @JsonFormat(pattern = "MM月dd日", timezone = "GMT+8")
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column film_arrangement.time
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    @JsonFormat(pattern = "HH:mm", timezone = "GMT+8")
    private Date time;

    @JsonFormat(pattern = "HH:mm", timezone = "GMT+8")
    private Date offTime;

    private String language;
}