package com.wyl.tms.model;

import com.baomidou.mybatisplus.annotations.TableField;
import com.baomidou.mybatisplus.annotations.TableId;
import com.baomidou.mybatisplus.annotations.TableName;
import com.baomidou.mybatisplus.enums.IdType;
import com.fasterxml.jackson.annotation.JsonFormat;
import lombok.Data;

import java.util.Date;

@TableName("film_info")
@Data
public class FilmInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column film_info.filmId
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    @TableId(value = "film_id", type = IdType.AUTO)
    private Integer filmId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column film_info.filmName
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    @TableField("film_name")
    private String filmName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column film_info.putOnDate
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    @JsonFormat(pattern = "yyyy-MM-dd", timezone = "GMT+8")
    @TableField("put_on_date")
    private Date putOnDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column film_info.putOffDate
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    @JsonFormat(pattern = "yyyy-MM-dd", timezone = "GMT+8")
    @TableField("put_off_date")
    private Date putOffDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column film_info.ticketPrice
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    @TableField("ticket_price")
    private Double ticketPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column film_info.filmType
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    @TableField("film_type")
    private Integer filmType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column film_info.filmDuration
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    @TableField("film_duration")
    private Integer filmDuration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column film_info.director
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    private String director;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column film_info.mainActor
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    @TableField("main_actor")
    private String mainActor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column film_info.introduction
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    private String introduction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column film_info.country
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    private String country;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column film_info.language
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    private String language;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column film_info.filmAvgScore
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    @TableField("film_avg_score")
    private Double filmAvgScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column film_info.filmStatus
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    @TableField("film_status")
    private Integer filmStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column film_info.isEnabled
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    @TableField("is_enabled")
    private Boolean isEnabled;

    private String url;
}