package com.wyl.tms.model;

import com.baomidou.mybatisplus.annotations.TableId;
import com.baomidou.mybatisplus.enums.IdType;
import lombok.Data;

@Data
public class MemberInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_info.memberId
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    @TableId(value = "member_id", type = IdType.AUTO)
    private Integer memberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_info.userId
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_info.memberTypeId
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    private Integer memberTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_info.name
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_info.telephone
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_info.balance
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    private Double balance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_info.totalRecharge
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    private Double totalRecharge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_info.payPassword
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    private String payPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_info.totalSave
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    private Double totalSave;

}