package com.wyl.tms.model;

public class MemberType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_type.memberTypeId
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    private Boolean memberTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_type.memberTypeName
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    private String memberTypeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_type.discount
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    private Double discount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_type.memberTypeId
     *
     * @return the value of member_type.memberTypeId
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public Boolean getMemberTypeId() {
        return memberTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_type.memberTypeId
     *
     * @param memberTypeId the value for member_type.memberTypeId
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public void setMemberTypeId(Boolean memberTypeId) {
        this.memberTypeId = memberTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_type.memberTypeName
     *
     * @return the value of member_type.memberTypeName
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public String getMemberTypeName() {
        return memberTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_type.memberTypeName
     *
     * @param memberTypeName the value for member_type.memberTypeName
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public void setMemberTypeName(String memberTypeName) {
        this.memberTypeName = memberTypeName == null ? null : memberTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_type.discount
     *
     * @return the value of member_type.discount
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public Double getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_type.discount
     *
     * @param discount the value for member_type.discount
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public void setDiscount(Double discount) {
        this.discount = discount;
    }
}