package com.wyl.tms.model;

public class SeatInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seat_info.seatId
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    private Integer seatId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seat_info.filmHallNumber
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    private Integer filmHallNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seat_info.sequence
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    private Integer sequence;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seat_info.seatRow
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    private Boolean seatRow;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seat_info.seatColumn
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    private Boolean seatColumn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seat_info.isEnabled
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    private Boolean isEnabled;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seat_info.seatId
     *
     * @return the value of seat_info.seatId
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public Integer getSeatId() {
        return seatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seat_info.seatId
     *
     * @param seatId the value for seat_info.seatId
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public void setSeatId(Integer seatId) {
        this.seatId = seatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seat_info.filmHallNumber
     *
     * @return the value of seat_info.filmHallNumber
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public Integer getFilmHallNumber() {
        return filmHallNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seat_info.filmHallNumber
     *
     * @param filmHallNumber the value for seat_info.filmHallNumber
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public void setFilmHallNumber(Integer filmHallNumber) {
        this.filmHallNumber = filmHallNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seat_info.sequence
     *
     * @return the value of seat_info.sequence
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public Integer getSequence() {
        return sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seat_info.sequence
     *
     * @param sequence the value for seat_info.sequence
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public void setSequence(Integer sequence) {
        this.sequence = sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seat_info.seatRow
     *
     * @return the value of seat_info.seatRow
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public Boolean getSeatRow() {
        return seatRow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seat_info.seatRow
     *
     * @param seatRow the value for seat_info.seatRow
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public void setSeatRow(Boolean seatRow) {
        this.seatRow = seatRow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seat_info.seatColumn
     *
     * @return the value of seat_info.seatColumn
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public Boolean getSeatColumn() {
        return seatColumn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seat_info.seatColumn
     *
     * @param seatColumn the value for seat_info.seatColumn
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public void setSeatColumn(Boolean seatColumn) {
        this.seatColumn = seatColumn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seat_info.isEnabled
     *
     * @return the value of seat_info.isEnabled
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public Boolean getIsEnabled() {
        return isEnabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seat_info.isEnabled
     *
     * @param isEnabled the value for seat_info.isEnabled
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public void setIsEnabled(Boolean isEnabled) {
        this.isEnabled = isEnabled;
    }
}