package com.wyl.tms.model;

public class SeatSelectionSituation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seat_selection_situation.seatSelectionId
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    private Integer seatSelectionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seat_selection_situation.arrangementId
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    private Integer arrangementId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seat_selection_situation.filmOrderId
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    private Integer filmOrderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seat_selection_situation.seatStatus
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    private Boolean seatStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seat_selection_situation.seatSelectionId
     *
     * @return the value of seat_selection_situation.seatSelectionId
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public Integer getSeatSelectionId() {
        return seatSelectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seat_selection_situation.seatSelectionId
     *
     * @param seatSelectionId the value for seat_selection_situation.seatSelectionId
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public void setSeatSelectionId(Integer seatSelectionId) {
        this.seatSelectionId = seatSelectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seat_selection_situation.arrangementId
     *
     * @return the value of seat_selection_situation.arrangementId
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public Integer getArrangementId() {
        return arrangementId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seat_selection_situation.arrangementId
     *
     * @param arrangementId the value for seat_selection_situation.arrangementId
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public void setArrangementId(Integer arrangementId) {
        this.arrangementId = arrangementId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seat_selection_situation.filmOrderId
     *
     * @return the value of seat_selection_situation.filmOrderId
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public Integer getFilmOrderId() {
        return filmOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seat_selection_situation.filmOrderId
     *
     * @param filmOrderId the value for seat_selection_situation.filmOrderId
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public void setFilmOrderId(Integer filmOrderId) {
        this.filmOrderId = filmOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seat_selection_situation.seatStatus
     *
     * @return the value of seat_selection_situation.seatStatus
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public Boolean getSeatStatus() {
        return seatStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seat_selection_situation.seatStatus
     *
     * @param seatStatus the value for seat_selection_situation.seatStatus
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public void setSeatStatus(Boolean seatStatus) {
        this.seatStatus = seatStatus;
    }
}