package com.wyl.tms.model;

import com.baomidou.mybatisplus.annotations.TableId;
import com.baomidou.mybatisplus.enums.IdType;
import lombok.Data;

@Data
public class SeatSelectionSituation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seat_selection_situation.seatSelectionId
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    @TableId(value = "seat_selection_id", type = IdType.AUTO)
    private Integer seatSelectionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seat_selection_situation.arrangementId
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    private Integer arrangementId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seat_selection_situation.filmOrderId
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    private Integer filmOrderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seat_selection_situation.seatStatus
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    private Integer seatStatus;

    private Integer seatId;

}