package com.wyl.tms.model;

import com.baomidou.mybatisplus.annotations.TableId;
import com.baomidou.mybatisplus.enums.IdType;

public class TheaterInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column theater_info.theaterId
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    @TableId(value = "theater_id", type = IdType.AUTO)
    private Integer theaterId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column theater_info.theaterName
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    private String theaterName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column theater_info.theaterAddress
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    private String theaterAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column theater_info.phoneNumber
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    private String phoneNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column theater_info.theaterDescription
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    private String theaterDescription;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column theater_info.theaterId
     *
     * @return the value of theater_info.theaterId
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public Integer getTheaterId() {
        return theaterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column theater_info.theaterId
     *
     * @param theaterId the value for theater_info.theaterId
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public void setTheaterId(Integer theaterId) {
        this.theaterId = theaterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column theater_info.theaterName
     *
     * @return the value of theater_info.theaterName
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public String getTheaterName() {
        return theaterName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column theater_info.theaterName
     *
     * @param theaterName the value for theater_info.theaterName
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public void setTheaterName(String theaterName) {
        this.theaterName = theaterName == null ? null : theaterName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column theater_info.theaterAddress
     *
     * @return the value of theater_info.theaterAddress
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public String getTheaterAddress() {
        return theaterAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column theater_info.theaterAddress
     *
     * @param theaterAddress the value for theater_info.theaterAddress
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public void setTheaterAddress(String theaterAddress) {
        this.theaterAddress = theaterAddress == null ? null : theaterAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column theater_info.phoneNumber
     *
     * @return the value of theater_info.phoneNumber
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column theater_info.phoneNumber
     *
     * @param phoneNumber the value for theater_info.phoneNumber
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber == null ? null : phoneNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column theater_info.theaterDescription
     *
     * @return the value of theater_info.theaterDescription
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public String getTheaterDescription() {
        return theaterDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column theater_info.theaterDescription
     *
     * @param theaterDescription the value for theater_info.theaterDescription
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public void setTheaterDescription(String theaterDescription) {
        this.theaterDescription = theaterDescription == null ? null : theaterDescription.trim();
    }
}