package com.wyl.tms.model;

public class UserGoodsOrder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_goods_order.goodsOrderId
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    private Integer goodsOrderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_goods_order.userId
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_goods_order.childGoodsOrderId
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    private Integer childGoodsOrderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_goods_order.couponId
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    private Integer couponId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_goods_order.goodsOrderPrice
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    private Double goodsOrderPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_goods_order.actualPayPrice
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    private Double actualPayPrice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_goods_order.goodsOrderId
     *
     * @return the value of user_goods_order.goodsOrderId
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public Integer getGoodsOrderId() {
        return goodsOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_goods_order.goodsOrderId
     *
     * @param goodsOrderId the value for user_goods_order.goodsOrderId
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public void setGoodsOrderId(Integer goodsOrderId) {
        this.goodsOrderId = goodsOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_goods_order.userId
     *
     * @return the value of user_goods_order.userId
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_goods_order.userId
     *
     * @param userId the value for user_goods_order.userId
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_goods_order.childGoodsOrderId
     *
     * @return the value of user_goods_order.childGoodsOrderId
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public Integer getChildGoodsOrderId() {
        return childGoodsOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_goods_order.childGoodsOrderId
     *
     * @param childGoodsOrderId the value for user_goods_order.childGoodsOrderId
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public void setChildGoodsOrderId(Integer childGoodsOrderId) {
        this.childGoodsOrderId = childGoodsOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_goods_order.couponId
     *
     * @return the value of user_goods_order.couponId
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public Integer getCouponId() {
        return couponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_goods_order.couponId
     *
     * @param couponId the value for user_goods_order.couponId
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public void setCouponId(Integer couponId) {
        this.couponId = couponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_goods_order.goodsOrderPrice
     *
     * @return the value of user_goods_order.goodsOrderPrice
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public Double getGoodsOrderPrice() {
        return goodsOrderPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_goods_order.goodsOrderPrice
     *
     * @param goodsOrderPrice the value for user_goods_order.goodsOrderPrice
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public void setGoodsOrderPrice(Double goodsOrderPrice) {
        this.goodsOrderPrice = goodsOrderPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_goods_order.actualPayPrice
     *
     * @return the value of user_goods_order.actualPayPrice
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public Double getActualPayPrice() {
        return actualPayPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_goods_order.actualPayPrice
     *
     * @param actualPayPrice the value for user_goods_order.actualPayPrice
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public void setActualPayPrice(Double actualPayPrice) {
        this.actualPayPrice = actualPayPrice;
    }
}