package com.wyl.tms.model;

public class UserTheaterInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_theater_info.userTheaterInfoId
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    private Integer userTheaterInfoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_theater_info.userId
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_theater_info.theaterId
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    private Integer theaterId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_theater_info.goToFrequency
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    private Integer goToFrequency;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_theater_info.isFavorites
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    private Boolean isFavorites;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_theater_info.userTheaterInfoId
     *
     * @return the value of user_theater_info.userTheaterInfoId
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public Integer getUserTheaterInfoId() {
        return userTheaterInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_theater_info.userTheaterInfoId
     *
     * @param userTheaterInfoId the value for user_theater_info.userTheaterInfoId
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public void setUserTheaterInfoId(Integer userTheaterInfoId) {
        this.userTheaterInfoId = userTheaterInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_theater_info.userId
     *
     * @return the value of user_theater_info.userId
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_theater_info.userId
     *
     * @param userId the value for user_theater_info.userId
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_theater_info.theaterId
     *
     * @return the value of user_theater_info.theaterId
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public Integer getTheaterId() {
        return theaterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_theater_info.theaterId
     *
     * @param theaterId the value for user_theater_info.theaterId
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public void setTheaterId(Integer theaterId) {
        this.theaterId = theaterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_theater_info.goToFrequency
     *
     * @return the value of user_theater_info.goToFrequency
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public Integer getGoToFrequency() {
        return goToFrequency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_theater_info.goToFrequency
     *
     * @param goToFrequency the value for user_theater_info.goToFrequency
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public void setGoToFrequency(Integer goToFrequency) {
        this.goToFrequency = goToFrequency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_theater_info.isFavorites
     *
     * @return the value of user_theater_info.isFavorites
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public Boolean getIsFavorites() {
        return isFavorites;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_theater_info.isFavorites
     *
     * @param isFavorites the value for user_theater_info.isFavorites
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public void setIsFavorites(Boolean isFavorites) {
        this.isFavorites = isFavorites;
    }
}