package com.wyl.tms.model;

import com.baomidou.mybatisplus.annotations.TableId;
import com.baomidou.mybatisplus.enums.IdType;
import lombok.Data;

import java.util.Date;

@Data
public class UserFilmOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_film_order.filmOrderId
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    @TableId(value = "film_order_id", type = IdType.AUTO)
    private Integer filmOrderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_film_order.arrangementId
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    private Integer arrangementId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_film_order.userId
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_film_order.orderStatus
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    private Integer orderStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_film_order.createdTime
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    private Date createdTime;

    private Double orderAmount;

    private Integer ticketQuantity;
}