package com.wyl.tms.model;

import com.baomidou.mybatisplus.annotations.TableId;
import com.baomidou.mybatisplus.enums.IdType;
import lombok.NoArgsConstructor;

import java.util.Date;

@NoArgsConstructor
public class User{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userId
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    @TableId(value = "user_id", type = IdType.AUTO)
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.nickname
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    private String nickname;

    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.sex
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    private Integer sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.telephone
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    private String telephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.loginPassword
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.headPhotoURL
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    private String headPhotoURL;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.birthday
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.isMember
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    private Integer isMember;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.integral
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    private Integer integral;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userId
     *
     * @return the value of user.userId
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userId
     *
     * @param userId the value for user.userId
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.nickname
     *
     * @return the value of user.nickname
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.nickname
     *
     * @param nickname the value for user.nickname
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.sex
     *
     * @return the value of user.sex
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.sex
     *
     * @param sex the value for user.sex
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.telephone
     *
     * @return the value of user.telephone
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.telephone
     *
     * @param telephone the value for user.telephone
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.loginPassword
     *
     * @return the value of user.loginPassword
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.headPhotoURL
     *
     * @return the value of user.headPhotoURL
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public String getHeadPhotoURL() {
        return headPhotoURL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.headPhotoURL
     *
     * @param headPhotoURL the value for user.headPhotoURL
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public void setHeadPhotoURL(String headPhotoURL) {
        this.headPhotoURL = headPhotoURL == null ? null : headPhotoURL.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.birthday
     *
     * @return the value of user.birthday
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.birthday
     *
     * @param birthday the value for user.birthday
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.isMember
     *
     * @return the value of user.isMember
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public Integer getIsMember() {
        return isMember;
    }

    public void setIsMember(Integer isMember) {
        this.isMember = isMember;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.integral
     *
     * @return the value of user.integral
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public Integer getIntegral() {
        return integral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.integral
     *
     * @param integral the value for user.integral
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public void setIntegral(Integer integral) {
        this.integral = integral;
    }

    public User(String username, String password) {
        this.username = username;
        this.password = password;
    }
}