package com.wyl.tms.model;

import java.util.Date;

public class UserFilmOrder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_film_order.filmOrderId
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    private Integer filmOrderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_film_order.arrangementId
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    private Integer arrangementId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_film_order.userId
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_film_order.parentOrderId
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    private Integer parentOrderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_film_order.seatId
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    private Integer seatId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_film_order.orderStatus
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    private Boolean orderStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_film_order.createdTime
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    private Date createdTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_film_order.filmOrderId
     *
     * @return the value of user_film_order.filmOrderId
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public Integer getFilmOrderId() {
        return filmOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_film_order.filmOrderId
     *
     * @param filmOrderId the value for user_film_order.filmOrderId
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public void setFilmOrderId(Integer filmOrderId) {
        this.filmOrderId = filmOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_film_order.arrangementId
     *
     * @return the value of user_film_order.arrangementId
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public Integer getArrangementId() {
        return arrangementId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_film_order.arrangementId
     *
     * @param arrangementId the value for user_film_order.arrangementId
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public void setArrangementId(Integer arrangementId) {
        this.arrangementId = arrangementId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_film_order.userId
     *
     * @return the value of user_film_order.userId
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_film_order.userId
     *
     * @param userId the value for user_film_order.userId
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_film_order.parentOrderId
     *
     * @return the value of user_film_order.parentOrderId
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public Integer getParentOrderId() {
        return parentOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_film_order.parentOrderId
     *
     * @param parentOrderId the value for user_film_order.parentOrderId
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public void setParentOrderId(Integer parentOrderId) {
        this.parentOrderId = parentOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_film_order.seatId
     *
     * @return the value of user_film_order.seatId
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public Integer getSeatId() {
        return seatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_film_order.seatId
     *
     * @param seatId the value for user_film_order.seatId
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public void setSeatId(Integer seatId) {
        this.seatId = seatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_film_order.orderStatus
     *
     * @return the value of user_film_order.orderStatus
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public Boolean getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_film_order.orderStatus
     *
     * @param orderStatus the value for user_film_order.orderStatus
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public void setOrderStatus(Boolean orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_film_order.createdTime
     *
     * @return the value of user_film_order.createdTime
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_film_order.createdTime
     *
     * @param createdTime the value for user_film_order.createdTime
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }
}